### PR TITLE
let develop be data-able, plus some reflowing stuff 

### PR DESCRIPTION
**Pull request by diaza**
The only files to check are the ones without module1 or module2 in the filename, src/proto_nd_flow/reco/charge/raw_event_generator.py and src/proto_nd_flow/reco/charge/calib_prompt_hits.py, which needed to be made data-able. 
The rest is reflow stuff that got caught in this messy branch.

### CODE REVIEW

**Comment by diaza** [comment]
Looped in @edhinkle in case they had qualms about their commits being pulled in

**Comment by edhinkle** [comment]
Thanks for checking in! While almost all the changes in my commits only affect Module 1 simulation and/or data reflowing, it looks like I made two small changes to `data/proto_nd_flow/2x2.yaml` in aafba85897962bf096b77b57d9c7bac865d12d1f to two light MC parameters, `max_light_truth_ids` and 
`mc_truth_threshold`. I can't recall exactly why these changes were included in this particular commit/branch, and it very well could have been a mistake on my part. Either way, I don't think it's a huge deal because it's only two parameters/lines, but this is the only change I made which I think might warrant further scrutiny.

**Review by krwood — COMMENTED** [review]
As a sanity check, can we process a simulation file from MR6 with this branch and have a look at the validation plots?

**Comment by mjkramer** [comment]
Output on MC looks good (see attachments). Had to do some manual reconciling of calib_prompt_hits.py, so @diaza you might want to test `develop` on module1 data after this is merged. The changes to 2x2.yaml won't cause any problems (only relevant for larnd-sim, plus in (bad) practice we overwrite 2x2.yaml with larnd-sim's version during installation of ndlar_flow).
[out.0000123.merged.hdf5_validations.pdf](https://github.com/user-attachments/files/17877796/out.0000123.merged.hdf5_validations.pdf)
[out.0000123.develop.hdf5_validations.pdf](https://github.com/user-attachments/files/17877797/out.0000123.develop.hdf5_validations.pdf)

**Pull request merged**
