### PR TITLE
mc_truth/interaction + true_pos in prompt_hit + backtrack

### PR DESCRIPTION
**Pull request by YifanC**
- Fill mc_truth/interactions with vertices when there is no mc_hdr available. (closed PR #126 )
- Added true drift position and true energy reconstructed hits. (closed PR #127 )
- Adapted to use configuration instead hardcoded numbers for hit reconstruction (closed PR #127 )
- Copy the `mc_packets_assn` from larndsim output to `mc_truth/packet_fraction` and propagate it to `mc_truth/calib_prompt_hit_backtrack`
- Adapted calib_hit_merger.py to consume the updated `mc_truth/calib_prompt_hit_backtrack` instead.
- Use index for referencing between the packet and segment instead of taking `segment_id` as indices for references. Together with [this PR for larndsim](https://github.com/DUNE/larnd-sim/pull/236), we can get rid of the hotfix for segment updates.

Note:
- `event_ids` are now available in `mc_truth/packet_fraction` and `mc_truth/calib_prompt_hit_backtrack`. `event_id` is not yet available in `mc_truth/calib_final_hit_backtrack` (to be added). `mc_truth/calib_final_hit_backtrack` data type is still defined manually, which can be updated too.
- In the backtracking datasets, `segment_ids` is used instead `segment_id` given this is what's been called in larnd-sim. We can change the name in larndsim if it's preferred. In truth dataset, we use `segment_id`.
- The data and ref all look reasonable to me. From validating the output of`mc_truth/calib_final_hit_backtrack`, I noticed some differences using this feature branch vs. using develop (commit [f58217e](https://github.com/DUNE/ndlar_flow/commit/f58217e27e9d8597be46102dc9d80ac2f37fe10e)). The differences are inherited from `mc_truth/calib_prompt_hit_backtrack`. Given in this feature branch it's a direct copy from the larndsim ouput and the develop version reshape and remask a few times, I am convinced the problem is in the develop branch, but I cannot explain what was wrong.

### CODE REVIEW

**Comment by YifanC** [comment]
Minor comments in Git Issue #129

**Comment by YifanC** [comment]
Some screenshots of some output: https://indico.fnal.gov/event/64988/contributions/293232/attachments/178588/243452/2024_06_04_ndlar_flow_readiness.pdf

**Review by mjkramer — APPROVED** [review]
Validation plots look identical to MR5-beta1

**Comment by YifanC** [comment]
> Validation plots look identical to MR5-beta1

Cool! @mjkramer Thanks for checking! I think we should add some backtracking part in the sim flow validation plots. (The backtracking info are different in beta1 and this version. The beta1 or current develop version doesn't seem to be correct.)

**Comment by diaza** [comment]
Could I ask what "true energy reconstructed hits" means? Is it the true charge deposited on the pixels, or the true dE deposited in the argon?

**Comment by YifanC** [comment]
@diaza `E_true_recomb_elife` means using true drift time and true dEdx for recombination to correct the energy of the hits. Note that I manually put the true lifetime in the config.

**Pull request merged**
